name: serializable_core
version: 0.11.1
description: generates a serializable class from classes using `source_gen` package
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/serializable_core

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.33.0
  build: ^1.0.1
  source_gen: ^0.9.0
  built_mirrors_core: ^0.10.1
#  built_mirrors_core:
#    path: ../built_mirrors_core
