name: serializable_core
version: 0.11.0+1
description: generates a serializable class from classes using `source_gen` package
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/serializable_core

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.32.0
  build: ^0.12.0
  source_gen: ^0.9.0
  built_mirrors_core: ^0.10.0
#  built_mirrors_core:
#    path: ../built_mirrors_core
